### ISSUE TITLE
JSF loss input stream and doesn't build pages correctly

### ISSUE THREAD

**Issue by javaserverfaces** [javaee/mojarra#4201]
Only on Linux never in Windows
O.S RedHat CentOS 6.6
WildFly 10.1
Mojarra 2.2.13

Sometime application lose render capability (pages aren't builted properly on server) and this is an stack a part of stacktrace
java.lang.NullPointerException
at com.sun.faces.application.resource.ResourceHelper$ELEvaluatingInputStream.close(ResourceHelper.java:856)
at java.io.BufferedInputStream.close(BufferedInputStream.java:483)
...

at javax.faces.application.ResourceHandlerWrapper.handleResourceRequest(ResourceHandlerWrapper.java:153)
at javax.faces.webapp.FacesServlet.service(FacesServlet.java:655)

Watching GrepCode I found the piece of code that throw the exception
@Override
851 public void More ...close() throws IOException {
852
853 if (endOfStreamReached && !expressionEvaluated)

{ 854 info.disableEL(); 855 }

856 inner.close();
857 super.close();
858
859 }

Where inner was teorically setted on
public More ...ELEvaluatingInputStream(FacesContext ctx,
682 ClientResourceInfo info,
683 InputStream inner)

{ 684 685 this.inner = inner; 686 this.info = info; 687 this.ctx = ctx; 688 689 }

Do you have any suggestion? Some timeout, some extra configuration or tips on linux system?
It's possible to catch the Exception and reinitialize in some way the application?

Vincenzo
#### Environment
RedHat CentOS 6.6.x
WildFly 8.2.1 and 10.x
#### Affected Versions
[2.2.8, 2.2.13]

**Comment by edburns** [comment]
Please see this important message regarding community contributions to
Mojarra.

https://javaee.groups.io/g/jsf-spec/message/30

Also, please consider joining that group, as that group has taken the
place of the old dev@javaserverfaces.java.net mailing list.

Thanks,

Ed Burns
