### ISSUE TITLE
UIComponentBase.validateId() thrown exception should be more explanatory

### ISSUE THREAD

**Issue by Quix0r** [javaee/mojarra#4375]
Please see following excerpt from a [thrown exception](https://f.haeder.net/display/adbba6c6645b411dbe70ea5438862510) I currently try to fix but I'm confused where (JSF template/view) it origins from.

````
java.lang.IllegalArgumentException:  
        at javax.faces.component.UIComponentBase.validateId(UIComponentBase.java:605)
        at javax.faces.component.UIComponentBase.setId(UIComponentBase.java:422)
        at com.sun.faces.facelets.tag.jsf.ComponentTagHandlerDelegateImpl.assignUniqueId(ComponentTagHandlerDelegateImpl.java:438)
[...]
````
It would be nice to have some message being added to that exception, like: `Invalid id x/y$z` or so then I can directly see where that exception comes from (one of my templates, of course).

JSF 2.3.5

**Comment by arjantijms** [comment]
I agree, the messages should be clearer here.

I’ve encountered this multiple times myself as well.

**Comment by Quix0r** [comment]
Any news here? I would really appreciate if this issue is quickly solved (and no big change, for sure). Maybe I can find some time to do it myself but no promise here.
