### ISSUE TITLE
ArrayIndexOutOfBoundsException in flash context ?

### ISSUE THREAD

**Issue by demanzano** [javaee/mojarra#4402]
Hi!

I'm using JSF Mojarra 2.3.9.SP01 (integrated in Wildfly 16.0.0) and since yesterday I'm having many of these messages in WF log:

`arraycopy: last source index 16 out of bounds for byte[15]: java.lang.ArrayIndexOutOfBoundsException: arraycopy: last source index 16 out of bounds for byte[15]
         at java.base/java.lang.System.arraycopy(Native Method)
         at com.sun.jsf-impl@2.3.9.SP01//com.sun.faces.util.ByteArrayGuardAESCTR.decrypt(ByteArrayGuardAESCTR.java:133)
         at com.sun.jsf-impl@2.3.9.SP01//com.sun.faces.context.flash.ELFlash$PreviousNextFlashInfoManager.decode(ELFlash.java:1391)
         at com.sun.jsf-impl@2.3.9.SP01//com.sun.faces.context.flash.ELFlash.getCurrentFlashManager(ELFlash.java:1214)
         at com.sun.jsf-impl@2.3.9.SP01//com.sun.faces.context.flash.ELFlash.doPrePhaseActions(ELFlash.java:618)
         at com.sun.jsf-impl@2.3.9.SP01//com.sun.faces.lifecycle.Phase.handleBeforePhase(Phase.java:190)
         at com.sun.jsf-impl@2.3.9.SP01//com.sun.faces.lifecycle.Phase.doPhase(Phase.java:74)
         at com.sun.jsf-impl@2.3.9.SP01//com.sun.faces.lifecycle.RestoreViewPhase.doPhase(RestoreViewPhase.java:109)
         at com.sun.jsf-impl@2.3.9.SP01//com.sun.faces.lifecycle.LifecycleImpl.execute(LifecycleImpl.java:177)
         at javax.faces.api@2.3.9.SP01//javax.faces.webapp.FacesServlet.executeLifecyle(FacesServlet.java:707)
`
I have no idea what happens, seems like a bug in flash context support, but I've never seen it in more than 2 years I'm using WF 10+

I also tried to upgrade to latest WF 17.0.1 with Mojarra 2.3.9.SP02 but no luck..
My app is using Primefaces 6.2.22 too.

Any idea is much welcome !

Thanks!

Ale

**Comment by leandrohsilveira** [comment]
Same here.
WildFly 17.0.1 with Mojarra 2.3.9.SP02.

PrimeFaces 6.2, OmniFaces 3.2 and PrettyFaces 3.4.1.Final.

**Comment by chrjohn** [comment]
Isn't this the same as #4386 ? Seems to be related to invalid cookie data.
